### ISSUE TITLE
Just some updates :wink: 

### ISSUE THREAD

**Issue by danielstokes** [ernst01/go-start-http-api#1]
I just saw that you made this public..

Could you upgrade go?  go 1.12 ??  

Update ssl certs?   `RUN apk add --update --no-cache ca-certificates` in your dockerfile

> Feel free to create Github Issues and Pull requests as you see fit.

Anyways, just some suggestions

**Comment by tebo-ernstberger** [comment]
Hi Daniel, 

The code base is 2 years old. I just created a tag yesterday as a base.
I'll push some updates soon.

Thanks,
